# Generated by Django 2.0.6 on 2020-11-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=22)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'User',
            },
        ),
        migrations.RenameField(
            model_name='author',
            old_name='id_delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='authordetail',
            old_name='id_delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='id_delete',
            new_name='is_delete',
        ),
        migrations.RenameField(
            model_name='press',
            old_name='id_delete',
            new_name='is_delete',
        ),
    ]
